### ISSUE TITLE
Layer instance has no attribute 'palette256' when set png options for a layer

### ISSUE THREAD

**Issue by timxi** [TileStache/TileStache#145]
I got the following error, when I set png optoins for a layer:

error message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/data/git/TileStache/TileStache/**init**.py", line 379, in **call**
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/opt/data/git/TileStache/TileStache/**init**.py", line 255, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/opt/data/git/TileStache/TileStache/Core.py", line 414, in getTileResponse
    tile = self.render(coord, format)
  File "/opt/data/git/TileStache/TileStache/Core.py", line 529, in render
    if self.palette256:
AttributeError: Layer instance has no attribute 'palette256'
ERROR:werkzeug:Error on request:
Traceback (most recent call last):

```
"contact":
{
    "provider": {"name": "mapnik", "mapfile": "examples/contact.xml"},
    "projection": "spherical mercator",
    "metatile": 
    {
        "rows": 4,
        "columns": 4,
        "buffer": 64
     },
    "png options":{
          "optimize": true
     }        
}
```

**Comment by gabefair** [comment]
I'm unable to load any layers other than `.png` 
![image](https://user-images.githubusercontent.com/2096785/34115779-863f595c-e3e4-11e7-8fe1-42dd54469387.png)

![image](https://user-images.githubusercontent.com/2096785/34115830-aae62d76-e3e4-11e7-890f-62488ec4595b.png)

![image](https://user-images.githubusercontent.com/2096785/34115881-d46350fc-e3e4-11e7-94ae-a5d9bc167c4a.png)

using url: 
![image](https://user-images.githubusercontent.com/2096785/34115966-0b5a1924-e3e5-11e7-921a-0315980a4a1b.png)
