### ISSUE TITLE
Mapbox Studio 'pbf' mbtiles aren't considered in MBTiles.py

### ISSUE THREAD

**Issue by jak2030** [TileStache/TileStache#211]
Using the workflow PostGIS --> Mapbox Studio --> Exported mbtile file, I've run into an issue.
The default export for a dataset in Mapbox Studio is `pbf` and the Tilestache MBTiles.py script doesn't support `pbf` format.

```python
formats = {'png': 'image/png', 'jpg': 'image/jpeg', 'json': 'application/json', None: None}
format = db.execute("SELECT value FROM metadata WHERE name='format'").fetchone()
format = format and format[0] or None
mime_type = formats[format]
```

When trying to load:

```json
{
  "cache":  {"...":"..."},
  "layers": 
  {
    "example":
    {
        "provider": {"name": "mbtiles", "tileset": "example.mbtiles"}
    } 
  }
}
```

I get the following traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 381, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 254, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 425, in getTileResponse
    tile = self.render(coord, format)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 511, in render
    tile = provider.renderTile(width, height, srs, coord)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/MBTiles.py", line 217, in renderTile
    mime_type, content = get_tile(self.tileset, coord)
  File "/home/ubuntu/.virtualenvs/smoke/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/MBTiles.py", line 159, in get_tile
    mime_type = formats[format]
KeyError: 'pbf'
```

Manually changing the metadata key/value in the mbtiles with sqlite doesn't solve the problem, nor does attempting manual conversion with [mb-util] (https://github.com/mapbox/mbutil).

**Comment by juliomalegria** [comment]
Could you share a link to the mbtiles files (or a small version of it) here?

**Comment by juliomalegria** [comment]
Your goal is to serve pbf tiles? Or would you like to convert them to jpg/png on the fly?

**Comment by jak2030** [comment]
I would happily serve jpg/png but

a) Tilemill isn't working for me (OSX 10.10.2) 
b) Mapbox Studio doesn't seem to allow customizing exports of .mbtiles, so I'm stuck with whatever they've set as default. 

Here is a sample of what Mapbox Studio exports:

https://www.dropbox.com/s/lyne31hdkdbj8kg/sample.mbtiles?dl=0

**Comment by juliomalegria** [comment]
Hey @jak2030,
So this is a .mbtiles file with Mapbox vector tiles encoded as pbf. TileStache doesn't support this format. If you find a way to export these tiles to json, png, or jpg, you could use the MBTiles provider. The other option is to export to a format that GDAL could read (and use the Mapnik provider instead).

I think you should ask this question in the [mapbox-studio](https://github.com/mapbox/mapbox-studio) repo.

**Comment by jak2030** [comment]
Ok, thanks a lot for the help!
