### ISSUE TITLE
Seeding to S3 causes error

### ISSUE THREAD

**Issue by jak2030** [TileStache/TileStache#216]
Trying to seed to s3, i.e.:

`./scripts/tilestache-seed.py -c ./TileStache/tilestache.cfg -e geojson 10 11 12 -l database_table -b 33.6478079 -84.5518189 33.8876179 -84.289389  --to-s3 access secret bucket`

Yields:

```
1 of 3543... Failed database_table/10/271/409.geojson, will try no more.
Traceback (most recent call last):
  File "./scripts/tilestache-seed.py", line 344, in <module>
    layer, coord, extension, options.ignore_cached)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 66, in getTile
    status_code, headers, body = layer.getTileResponse(coord, extension, ignore_cached)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 386, in getTileResponse
    body = cache.read(self, coord, format)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/S3.py", line 118, in read
    key = self.bucket.get_key(key_name)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 192, in get_key
    key, resp = self._get_key_internal(key_name, headers, query_args_l)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 199, in _get_key_internal
    query_args=query_args)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/ubuntu/.virtualenvs/some_env/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.gaierror: [Errno -2] Name or service not known
```

I have tried a number of iterations (I have the AWS credentials stored as environment variables, etc.), but always come up with this error wherein seeding tries to call an s3 bucket rather than write to it first.

I would assume the behavior should be writing geojson to s3 and then calling `cache.read` as it does in the traceback above. If I am misunderstanding the use of seed and this issue is not an actual bug, then clarification in the documentation would be amazing!

Thank you.

**Comment by mappingvermont** [comment]
I'm experiencing the same issue. Not sure how to solve it; will likely just write to disk and then push to s3 using s4cmd.

**Comment by mappingvermont** [comment]
I've reread the tilestache docs, and I think it may have something to do with the bucket specified. I was using the following config: 
```
{
  "cache":
  {
    "name": "S3",
    "bucket": "wri-tiles/glad_test/dev"
  },
  "layers":
  {
    "tiles": {
      "provider" : {
        "name": "mapnik", "mapfile": "~/glad/glad-processing-gdal/tiles/config/africa/z_12.xml"
      }
    }
  }
}
```

And modified it to split the `bucket` object into `bucket` and `path`. Works great now.
```
  "cache":
  {
    "name": "S3",
    "bucket": "wri-tiles",
    "path": "glad_test/dev",
    "use_locks": "False"
  },
  "layers":
  {
    "tiles": {
      "provider" : {
        "name": "mapnik", "mapfile": "~/glad/glad-processing-gdal/tiles/config/africa/z_11.xml"
      }
    }
  }
}
```
