### ISSUE TITLE
Problems with MVT

### ISSUE THREAD

**Issue by vespakoen** [TileStache/TileStache#222]
Hey!

Thanks for TileStache, it's great!
I am trying to turn GeoJSON into the MVT format, at first, I added a vector provider with type GeoJSON, pointed it to the geojson file, and I was able to get data out of TileStache, but not in the MVT format.

I am guessing I have to insert the data into PostgreSQL first, so that is what I did.

My geojson looks like this:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "crs":{"type":"name","properties":{"name":"EPSG:4326"}},
        "coordinates": [
          ...
```

I then imported this data into postgresql like this:
```shell
ogr2ogr -update -append -f PostgreSQL "PG:dbname=ts_data host=localhost port=5432 user=gis" roadtrip.geojson
```

Then, I started the TileStache server using the following TileStache config:
```json
{
  "cache": {
    "name": "Test",
    "path": "/tmp/stache",
    "umask": "0000"
  },
  "layers": {
    "roadtrip": {
      "allowed origin": "*",
      "provider": {
        "class": "TileStache.Goodies.VecTiles:Provider",
        "kwargs": {
          "dbinfo": {
            "host": "localhost",
            "user": "gis",
            "password": "gis",
            "database": "ts_data"
          },
          "queries": [
            "SELECT ogc_fid AS gid, wkb_geometry AS __geometry__ FROM public.ogrgeojson"
          ]
        }
      }
    }
  }
}
```

Now, when I visit `http://localhost:1234/roadtrip/0/0/0.mvt` I get:
```
127.0.0.1 - - [12/Jul/2015 17:53:40] "GET /roadtrip/0/0/0.mvt HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 381, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 254, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 441, in getTileResponse
    tile.save(buff, format, **save_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/server.py", line 278, in save
    db.execute(self.query[format])
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
InternalError: Operation on mixed SRID geometries
127.0.0.1 - - [12/Jul/2015 17:53:40] "GET /favicon.ico HTTP/1.1" 400 -
```

So I modified the query to transform the geometry into the 900913 projection:
```sql
SELECT ogc_fid AS gid, ST_Transform(wkb_geometry, 900913) AS __geometry__ FROM public.ogrgeojson
```

This produces the following result:
```
127.0.0.1 - - [12/Jul/2015 17:55:14] "GET /roadtrip/0/0/0.mvt HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 381, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 254, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 441, in getTileResponse
    tile.save(buff, format, **save_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/server.py", line 297, in save
    mvt.encode(out, features)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/mvt.py", line 77, in encode
    wkb = approximate_wkb(feature[0])
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/wkb.py", line 139, in approximate_wkb
    approx_geometry(input, output)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/wkb.py", line 133, in approx_geometry
    raise ValueError(type)
ValueError: 1005
```

I also tried converting the projection while importing using the -s_srs and -t_srs flags as seen here:
```
ogr2ogr -s_srs "EPSG:4326" -t_srs "EPSG:900913" -update -append -f PostgreSQL "PG:dbname=ts_data host=localhost port=5432 user=trapps" roadtrip.geojson
```

This produces:
```
ERROR 6: EPSG PCS/GCS code 900913 not found in EPSG support files.  Is this a valid
EPSG coordinate system?
Failed to process SRS definition: EPSG:900913
```

Then I read this: http://lists.osgeo.org/pipermail/gdal-dev/2009-November/022672.html
And tried this:
```
ogr2ogr -s_srs "EPSG:4326" -t_srs "EPSG:3857" -update -append -f PostgreSQL "PG:dbname=ts_data host=localhost port=5432 user=trapps" roadtrip.geojson
```

Which ran successfully.
Now, I removed the ST_Transform from my query, and tried again, giving me this error again:

```
127.0.0.1 - - [12/Jul/2015 18:06:48] "GET /roadtrip/0/0/0.mvt HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 381, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 254, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 441, in getTileResponse
    tile.save(buff, format, **save_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/Goodies/VecTiles/server.py", line 278, in save
    db.execute(self.query[format])
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
InternalError: Operation on mixed SRID geometries
127.0.0.1 - - [12/Jul/2015 18:06:48] "GET /favicon.ico HTTP/1.1" 400 -
```

Now I am pretty much lost, and hope you guys can point me in the right direction.

**Comment by vespakoen** [comment]
Turns out my geojson contained data for the Z axis, using the following query I was able to produce some output from TileStache:

```sql
ALTER TABLE ogrgeojson
ALTER COLUMN wkb_geometry TYPE geometry(LineString, 900913) USING ST_Transform(ST_Force_2D(wkb_geometry), 900913);
```

However, when I try to parse this file like this:
```
var fs = require('fs');
var Protobuf = require('pbf');
var VectorTile = require('vector-tile').VectorTile;
var data = fs.readFileSync('./tile.pbf');
var tile = new VectorTile(new Protobuf(new Uint8Array(data)));
console.log(tile);
```

I get
```
home/koen/test/node_modules/pbf/index.js:204
        else throw new Error('Unimplemented type: ' + type);
                   ^
Error: Unimplemented type: 3
    at Object.Pbf.skip (/home/koen/test/node_modules/pbf/index.js:204:20)
    at Object.Pbf.readFields (/home/koen/test/node_modules/pbf/index.js:40:45)
    at new VectorTileLayer (/home/koen/test/node_modules/vector-tile/lib/vectortilelayer.js:20:9)
    at readTile (/home/koen/test/node_modules/vector-tile/lib/vectortile.js:13:21)
    at Object.Pbf.readFields (/home/koen/test/node_modules/pbf/index.js:38:13)
    at new VectorTile (/home/koen/test/node_modules/vector-tile/lib/vectortile.js:8:23)
    at Object.<anonymous> (/home/koen/test/test.js:11:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Anybody got a clue what's going on here?

Thanks
