### ISSUE TITLE
Sensible warnings for bad bbox

### ISSUE THREAD

**Issue by NineFX** [TileStache/TileStache#226]
Calls to `tilestache-seed.py` with a bad `bbox` return `math domain error`. It seems like a simple validation block could save the user some trouble.

```
tilestache-seed.py -b -125.0011 24.9493 -66.9326 49.5904 -c tilestache.cfg -l polygons

Traceback (most recent call last):
  File "/usr/local/bin/tilestache-seed.py", line 287, in <module>
    lr = layer.projection.locationCoordinate(southeast)
  File "/usr/local/lib/python2.7/site-packages/ModestMaps/Geo.py", line 132, in locationCoordinate
    point = self.project(point)
  File "/usr/local/lib/python2.7/site-packages/ModestMaps/Geo.py", line 119, in project
    point = self.rawProject(point)
  File "/usr/local/lib/python2.7/site-packages/ModestMaps/Geo.py", line 151, in rawProject
    math.log(math.tan(0.25 * math.pi + 0.5 * point.y)))
ValueError: math domain error
```

**Comment by juliomalegria** [comment]
Awesome idea! Fixed in 83d5541.
