### ISSUE TITLE
memcache config 

### ISSUE THREAD

**Issue by divya1c** [TileStache/TileStache#252]
Hi! 

I am trying to make memcache work for my server and I get this error : 

127.0.0.1 - - [14/Feb/2016 02:26:33] "GET /osm/10/167/396.png HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 381, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/usr/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/__init__.py", line 254, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/usr/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/Core.py", line 384, in getTileResponse
    body = cache.read(self, coord, format)
  File "/usr/local/lib/python2.7/site-packages/TileStache-1.50.1-py2.7.egg/TileStache/Memcache.py", line 106, in read
    mem = Client(self.servers)
NameError: global name 'Client' is not defined
127.0.0.1 - - [14/Feb/2016 02:26:33] "GET /osm/null HTTP/1.1" 400 -

My config is :

 "cache":
  {
    "name": "Memcache",
    "servers": ["127.0.0.1:11211"]
  }

Am I doing something wrong?
Thanks!

**Comment by divya1c** [comment]
Fixed it. Seems like my memcache python library wasn't installed.
