### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by aberenyi** [TileStache/TileStache#279]
Hi there - I was wondering whether this is something that you are considering to implement anytime soon?

In the meantime, I've tired `2to3` which seemingly converted the code just fine.

However, trying to access the main page I ran into a `NameError: name 'http' is not defined`, so I've added `import http` to `__init__.py`.

The next error seems to come from Werkzeug?
```bash
xxx.xxx.xxx.xxx - - [31/Jan/2017 19:56:43] "GET / HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/opt/virtualenv/lib/python3.5/site-packages/Werkzeug-0.11.13-py3.5.egg/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/opt/virtualenv/lib/python3.5/site-packages/Werkzeug-0.11.13-py3.5.egg/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/opt/virtualenv/lib/python3.5/site-packages/Werkzeug-0.11.13-py3.5.egg/werkzeug/serving.py", line 164, in write
    assert isinstance(data, bytes), 'applications must write bytes'
AssertionError: applications must write bytes
```
AFAIK Werkzeug does support Python3.

Any idea how to overcome this issue?

Cheers

**Comment by maxim-s-barabash** [comment]
To start using uwsgi. 
http://tilestache.org/doc/#wsgi

**Comment by migurski** [comment]
We recently upgraded many core components to Python 3 in https://github.com/TileStache/TileStache/pull/275, which I believe is release as of 1.51.5. There is a followup note in https://github.com/TileStache/TileStache/issues/276 to extend test coverage to ensure Python 3 compatibility in currently-untested packages. Would you be able to help with that?

**Comment by aberenyi** [comment]
@maxim-s-barabash thanks for the tip, I'll give that a go.

@migurski I'll do my best, however, I'm afraid I won't be able to carve out enough time for this in the near future.

**Comment by aberenyi** [comment]
@migurski I've forked the repo and [made it work](https://github.com/aberenyi/TileStache/tree/python3) for my specific use case. It can now serve mapnik grids, but I have not tested any other use case yet. I'll try to increase coverage and make sure that all tests pass.

**Comment by alculquicondor** [comment]
@aberenyi could you open a pull request marking it as WIP so that we can add comments to it?

**Comment by migurski** [comment]
I see a few places where `2to3` might have been too aggressive, such as switching in the Python 3 versions of an import in the Python 2 code path.

**Comment by aberenyi** [comment]
@migurski I completely agree, one has to manually go through that commit.

@alculquicondor sure.
