### ISSUE TITLE
run tile server with python3

### ISSUE THREAD

**Issue by josephzhao** [TileStache/TileStache#298]
Traceback (most recent call last):
  File "/opt/TileStache/scripts/tilestache-server.py", line 56, in <module>
    app = TileStache.WSGITileServer(config=options.file, autoreload=True)
  File "/usr/local/lib/python3.5/dist-packages/TileStache-1.51.6-py3.5.egg/TileStache/__init__.py", line 369, in __init__
    if type(config) in (str, unicode, dict):
NameError: name 'unicode' is not defined

python3

**Comment by radumas** [comment]
Python 3 support appears to be a work in progress. See #279

**Comment by gabefair** [comment]
I suspect that some of Tilestache's dependencies have dropped python 2 support.  `werkzeug` as an example.
