### ISSUE TITLE
Unhandled exception in WSGITileServer produces confusing error message

### ISSUE THREAD

**Issue by harto** [TileStache/TileStache#303]
I encountered a confusing error message while using `TileStache.Goodies.ExternalConfigServer.WSGIServer`:

```
Exception happened during processing of request from ('127.0.0.1', 63799)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

This happened when a tile was being written to a filesystem cache that didn't have the correct permissions set. But that error was swallowed by the one above.

I'm a new user of TileStache, so my apologies if I misunderstood. Let me know if I can provide more information.

**Comment by migurski** [comment]
This one’s odd. If there was another error, it might have prevented an HTTP status line from being generated, making `self.status` None?

**Comment by harto** [comment]
Yes, I think that's what happened. Perhaps a catch-all `except` should be introduced in either `TileStache.requestHandler2` or `TileStache.WSGITileServer.__call__`?
