### ISSUE TITLE
OSERROR encountered when requesting jpg tile outside of configured bounds

### ISSUE THREAD

**Issue by oderby** [TileStache/TileStache#355]
I have a jpeg layer that is configured with restricted bounds, and whenever I try to fetch a tile outside of those bounds, there appears to be an issue in rendering and returning the transparent empty tile. Abbreviated exception is included below. I believe the problem is that I've requested a JPEG tile (extension `jpg`) but the transparent tile is returned as an RGBA tile (https://github.com/TileStache/TileStache/blob/master/TileStache/Core.py#L484) and pillow is choking when trying to write it out to the buffer as a JPEG.

```
ERROR:flask.app:Exception on /my-layer/10/275/387.jpg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PIL/JpegImagePlugin.py", line 620, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/streetsdata/Streets_Data/__init__.py", line 225, in get_tilestache_tile
    '/{layer}/{z}/{x}/{y}.{ext}'.format(**locals()))
  File "/usr/local/lib/python3.6/dist-packages/TileStache/__init__.py", line 207, in requestHandler
    status_code, headers, content = requestHandler2(config_hint, path_info, query_string)
  File "/usr/local/lib/python3.6/dist-packages/TileStache/__init__.py", line 266, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/usr/local/lib/python3.6/dist-packages/TileStache/Core.py", line 443, in getTileResponse
    tile.save(buff, format, **save_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/dist-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
```

**Comment by rburhum** [comment]
There is no transparency in JPEGs https://stackoverflow.com/questions/9147883/only-png-supports-transparency-is-that-true

**Comment by oderby** [comment]
Yep, that's why pillow throws an error - it's safe to convert an RGBA image to PNG, but not to JPEG. 

The problem is that Tilestache is trying to return an RGBA image in response to a request for a JPEG tile, when the requested tile is out of bounds.
