### ISSUE TITLE
py3 compatibility?

### ISSUE THREAD

**Issue by JulieGoldberg** [TileStache/TileStache#366]
Is this project still being maintained? I still rely on it. Since python 2.7 was officially deprecated in January, I'm hoping there are plans to upgrade TileStache to python 3. 

What's the situation there?

**Comment by honglei** [comment]
NO， it not work under Python3
```
D:\ProgramData\Python38\Scripts>python ./tilestache-server.py
Traceback (most recent call last):
  File "D:\ProgramData\Python38\lib\site-packages\tilestache-1.51.14-py3.8.egg\TileStache\py3_compat.py", line 23, in <module>
    from cgi import parse_qs
ImportError: cannot import name 'parse_qs' from 'cgi' (D:\ProgramData\Python38\lib\cgi.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tilestache-server.py", line 4, in <module>
    __import__('pkg_resources').run_script('TileStache==1.51.14', 'tilestache-server.py')
  File "D:\ProgramData\Python38\lib\site-packages\pkg_resources\__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "D:\ProgramData\Python38\lib\site-packages\pkg_resources\__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "d:\programdata\python38\lib\site-packages\tilestache-1.51.14-py3.8.egg\EGG-INFO\scripts\tilestache-server.py", line 50, in <module>
    import TileStache
  File "D:\ProgramData\Python38\lib\site-packages\tilestache-1.51.14-py3.8.egg\TileStache\__init__.py", line 23, in <module>
    from .py3_compat import urljoin, urlparse, urlopen, parse_qs, httplib, is_string_type, reduce
  File "D:\ProgramData\Python38\lib\site-packages\tilestache-1.51.14-py3.8.egg\TileStache\py3_compat.py", line 28, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```

**Comment by honglei** [comment]
It can work after change a few changes.
